---
- name: Configure Managed Routers
  hosts: routers
  connection: network_cli 
  tasks:
  - include: tasks/backup.yml
  - include: tasks/add_domain_name.yml
  - include: tasks/MGMT_ACL.yml
  - include: tasks/create_sub_interfaces.yml
  - include: tasks/save_config.yml


